package fr.toss.FF7;

import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor.ArmorMaterial;
import net.minecraftforge.common.util.EnumHelper;
import fr.toss.FF7.armor.*;
import java.util.ArrayList;
import java.util.List;

public class ArmorRegistry {

	public static ArmorMaterial TUTORIAL_ARMOR = EnumHelper.addArmorMaterial("TUTORIAL_ARMOR", 16, new int[] {3, 8, 6, 3}, 30);
	
	
	
	
	public static List<Item> items = new ArrayList<Item>();

	    public static Item Bronzehelm;
	    public static Item Barbut;
	    public static Item Closehelmet;
	    public static Item Diamondhelm;
	    public static Item Genjihelm;
	    public static Item Giantshelmet;
	    public static Item Hanyamask;
	    public static Item Ironhelmet;
	    public static Item Platinumhelmet;
	    public static Item Barette;
	    public static Item Blackhat;
	    public static Item Cachusha;
	    public static Item Circlet;
	    public static Item Goldenskullcap;
	    public static Item Goldhairpin;
	    public static Item Greenberet;
	    public static Item Headband;
	    public static Item Plumedhat;
	    public static Item Ribbon;
	    public static Item Thiefscap;
	    public static Item Tiara;
	    public static Item Wizardshat;
	    public static Item Whitehat;
	    
	    public static Item Adamantarmor;
	    public static Item Adamantvest;
	    public static Item Aegisshield;
	    public static Item Blackgarb;
	    public static Item Blackrobe;
	    public static Item Blazerobe;
	    public static Item Boneplate;
	    public static Item Brigandine;
	    public static Item Brintfrock;
	    public static Item Bronzearmor;
	    public static Item Bronzeshield;
	    public static Item Carabineermail;
	    public static Item Chainmail;
	    public static Item Chameleonrobe;
	    public static Item Chocoboshield;
	    public static Item Diamondarmor;
	    public static Item Dragonmail;
	    public static Item Ensanguinedshield;
	    public static Item Everrobe;
	    public static Item flameshield;
	    public static Item flurryrobe;
	    public static Item Gaiagear;
	    public static Item Galmiafrock;
	    public static Item Galmiashoes;
	    public static Item Genjiarmor;
	    public static Item Genjishield;
	    public static Item Goldenarmor;
	    public static Item Hempenrobe;
	    public static Item Iceshield;
	    public static Item Ironarmor;
	    public static Item Judicerscoat;
	    public static Item Jujitsugi;
	    public static Item Leatherclothing;
	    public static Item Linencuirass;
	    public static Item Lordlyrobe;
	    public static Item Luminousrobe;
	    public static Item Magickrobe;
	    public static Item Magusrobe;
	    public static Item Materiaarmor;
	    public static Item Maximillian;
	    public static Item Minervabustier;
	    public static Item Miragevest;
	    public static Item Mirrormail;
	    public static Item Ninjagear;
	    public static Item Peytral;
	    public static Item Platemail;
	    public static Item Platinumarmor;
	    public static Item Platinumshield;
	    public static Item Powersash;
	    public static Item Reapersrobe;
	    public static Item Redrobe;
	    public static Item Reverieshield;
	    public static Item Roundshield;
	    public static Item Rubbersuit;
	    public static Item Sagesrobe;
	    public static Item Samitecoat;
	    public static Item Shieldofthefour;
	    public static Item Silkenrobe;
	    public static Item Survivalvest;
	    public static Item Templarcloth;
	    public static Item Templarshield;
	    public static Item Thunderrobe;
	    public static Item Whiterobe;
	    public static Item Wygar;
	    
	    public static Item Angelring;
	    public static Item Armguards;
	    public static Item Armletofwhispers;
	    public static Item Azuretear;
	    public static Item Battleboots;
	    public static Item Bonearmlets;
	    public static Item Bracers;
	    public static Item Brigandsgloves;
	    public static Item Condemnerschoker;
	    public static Item Corsageofcorruption;
	    public static Item Crimsontear;
	    public static Item Earringsofthedead;
	    public static Item Emphyrealarmband;
	    public static Item Ewerofdarkness;
	    public static Item Faerieshoes;
	    public static Item Fortunering;
	    public static Item Gaiuscaligae;
	    public static Item Gauntlets;
	    public static Item Genjigloves;
	    public static Item Germinasboots;
	    public static Item Giftofthejudgesal;
	    public static Item Gigaspendant;
	    public static Item Goldenamulet;
	    public static Item Highseraphsplume;
	    public static Item Magickring;
	    public static Item Moonmaiden;
	    public static Item Ninjatabi;
	    public static Item Orbofminwu;
	    public static Item Pinoforder;
	    public static Item Ragingbrooch;
	    public static Item Redshoes;
	    public static Item Ringofprecepts;
	    public static Item Ringofthewheel;
	    public static Item Rubyearring;
	    public static Item Scarabcharm;
	    public static Item Snowytear;
	    public static Item Spikedboots;
	    public static Item Sprintshoes;
	    public static Item Taintedcufflinks;
	    public static Item Wingedboots;
	   

	public static void init() {
		Bronzehelm = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Barbut = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Closehelmet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Diamondhelm = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Genjihelm = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Giantshelmet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Hanyamask = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ironhelmet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Platinumhelmet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Barette = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Blackhat = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Cachusha = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Circlet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Goldenskullcap = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Goldhairpin = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Greenberet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Headband = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Plumedhat = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ribbon = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Thiefscap = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Tiara = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Wizardshat = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Whitehat = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		
		Adamantarmor = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Adamantvest = new Adamantvest(TUTORIAL_ARMOR, 1, 1);
		Aegisshield = new Aegisshield(TUTORIAL_ARMOR, 1, 1);
		Blackgarb = new Blackgarb(TUTORIAL_ARMOR, 1, 1);
		Blackrobe = new Blackrobe(TUTORIAL_ARMOR, 1, 1);
		Blazerobe = new Blazerobe(TUTORIAL_ARMOR, 1, 1);
		Boneplate = new Boneplate(TUTORIAL_ARMOR, 1, 1);
		Brigandine = new Brigandine(TUTORIAL_ARMOR, 1, 1);
		Brintfrock = new Brintfrock(TUTORIAL_ARMOR, 1, 1);
		Bronzearmor = new Bronzearmor(TUTORIAL_ARMOR, 1, 1);
		Bronzeshield = new Bronzeshield(TUTORIAL_ARMOR, 1, 1);
		Carabineermail = new Carabineermail(TUTORIAL_ARMOR, 1, 1);
		Chainmail = new Chainmail(TUTORIAL_ARMOR, 1, 1);
		Chameleonrobe = new Chameleonrobe(TUTORIAL_ARMOR, 1, 1);
		Chocoboshield = new Chocoboshield(TUTORIAL_ARMOR, 1, 1);
		Diamondarmor = new Diamondarmor(TUTORIAL_ARMOR, 1, 1);
		Dragonmail = new Dragonmail(TUTORIAL_ARMOR, 1, 1);
		Ensanguinedshield = new Ensanguinedshield(TUTORIAL_ARMOR, 1, 1);
		Everrobe = new Everrobe(TUTORIAL_ARMOR, 1, 1);
		flameshield = new Flameshield(TUTORIAL_ARMOR, 1, 1);
		flurryrobe = new Flurryrobe(TUTORIAL_ARMOR, 1, 1);
		Gaiagear = new Gaiagear(TUTORIAL_ARMOR, 1, 1);
		Galmiafrock = new Galmiafrock(TUTORIAL_ARMOR, 1, 1);
		Galmiashoes = new Galmiashoes(TUTORIAL_ARMOR, 1, 1);
		Genjiarmor = new Genjiarmor(TUTORIAL_ARMOR, 1, 1);
		Genjishield = new Genjishield(TUTORIAL_ARMOR, 1, 1);
		Goldenarmor = new Goldenarmor(TUTORIAL_ARMOR, 1, 1);
		Hempenrobe = new Hempenrobe(TUTORIAL_ARMOR, 1, 1);
		Iceshield = new Iceshield(TUTORIAL_ARMOR, 1, 1);
		Ironarmor = new Ironarmor(TUTORIAL_ARMOR, 1, 1);
		Judicerscoat = new Judicerscoat(TUTORIAL_ARMOR, 1, 1);
		Jujitsugi = new Jujitsugi(TUTORIAL_ARMOR, 1, 1);
		Leatherclothing = new Leatherclothing(TUTORIAL_ARMOR, 1, 1);
		Linencuirass = new Linencuirass(TUTORIAL_ARMOR, 1, 1);
		Lordlyrobe = new Lordlyrobe(TUTORIAL_ARMOR, 1, 1);
		Luminousrobe = new Luminousrobe(TUTORIAL_ARMOR, 1, 1);
		Magickrobe = new Magickrobe(TUTORIAL_ARMOR, 1, 1);
		Magusrobe = new Magusrobe(TUTORIAL_ARMOR, 1, 1);
		Materiaarmor = new Materiaarmor(TUTORIAL_ARMOR, 1, 1);
		Maximillian = new Maximillian(TUTORIAL_ARMOR, 1, 1);
		Minervabustier = new Minervabustier(TUTORIAL_ARMOR, 1, 1);
		Miragevest = new Miragevest(TUTORIAL_ARMOR, 1, 1);
		Mirrormail = new Mirrormail(TUTORIAL_ARMOR, 1, 1);
		Ninjagear = new Ninjagear(TUTORIAL_ARMOR, 1, 1);
		Peytral = new Peytral(TUTORIAL_ARMOR, 1, 1);
		Platemail = new Platemail(TUTORIAL_ARMOR, 1, 1);
		Platinumarmor = new Platinumarmor(TUTORIAL_ARMOR, 1, 1);
		Platinumshield = new Platinumshield(TUTORIAL_ARMOR, 1, 1);
		Powersash = new Powersash(TUTORIAL_ARMOR, 1, 1);
		Reapersrobe = new Reapersrobe(TUTORIAL_ARMOR, 1, 1);
		Redrobe = new Redrobe(TUTORIAL_ARMOR, 1, 1);
		Reverieshield = new Reverieshield(TUTORIAL_ARMOR, 1, 1);
		Roundshield = new Roundshield(TUTORIAL_ARMOR, 1, 1);
		Rubbersuit = new Rubbersuit(TUTORIAL_ARMOR, 1, 1);
		Sagesrobe = new Sagesrobe(TUTORIAL_ARMOR, 1, 1);
		Samitecoat = new Samitecoat(TUTORIAL_ARMOR, 1, 1);
		Shieldofthefour = new Shieldofthefour(TUTORIAL_ARMOR, 1, 1);
		Silkenrobe = new Silkenrobe(TUTORIAL_ARMOR, 1, 1);
		Survivalvest = new Survivalvest(TUTORIAL_ARMOR, 1, 1);
		Templarcloth = new Templarcloth(TUTORIAL_ARMOR, 1, 1);
		Templarshield = new Templarshield(TUTORIAL_ARMOR, 1, 1);
		Thunderrobe = new Thunderrobe(TUTORIAL_ARMOR, 1, 1);
		Whiterobe = new Whiterobe(TUTORIAL_ARMOR, 1, 1);
		Wygar = new Wygar(TUTORIAL_ARMOR, 1, 1);
		
		Angelring = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Armguards = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Armletofwhispers = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Azuretear = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Battleboots = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Bonearmlets = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Bracers = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Brigandsgloves = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Condemnerschoker = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Corsageofcorruption = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Crimsontear = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Earringsofthedead = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Emphyrealarmband = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ewerofdarkness = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Faerieshoes = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Fortunering = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Gaiuscaligae = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Gauntlets = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Genjigloves = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Germinasboots = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Giftofthejudgesal = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Gigaspendant = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Goldenamulet = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Highseraphsplume = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Magickring = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Moonmaiden = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ninjatabi = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Orbofminwu = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Pinoforder = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ragingbrooch = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Redshoes = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ringofprecepts = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Ringofthewheel = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Rubyearring = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Scarabcharm = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Snowytear = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Spikedboots = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Sprintshoes = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Taintedcufflinks = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		Wingedboots = new Adamantarmor(TUTORIAL_ARMOR, 1, 1);
		
		
		GameRegistry.registerItem(Bronzehelm, "Bronzehelm" );
		GameRegistry.registerItem(Barbut, "Barbut" );
		GameRegistry.registerItem(Closehelmet, "Closehelmet" );
		GameRegistry.registerItem(Diamondhelm, "Diamondhelm" );
		GameRegistry.registerItem(Genjihelm, "Genjihelm" );
		GameRegistry.registerItem(Giantshelmet, "Giantshelmet" );
		GameRegistry.registerItem(Hanyamask, "Hanyamask" );
		GameRegistry.registerItem(Ironhelmet, "Ironhelmet" );
		GameRegistry.registerItem(Platinumhelmet, "Platinumhelmet" );
		GameRegistry.registerItem(Barette, "Barette" );
		GameRegistry.registerItem(Blackhat, "Blackhat" );
		GameRegistry.registerItem(Cachusha, "Cachusha" );
		GameRegistry.registerItem(Circlet, "Circlet" );
		GameRegistry.registerItem(Goldenskullcap, "Goldenskullcap" );
		GameRegistry.registerItem(Goldhairpin, "Goldhairpin" );
		GameRegistry.registerItem(Greenberet, "Greenberet" );
		GameRegistry.registerItem(Headband, "Headband" );
		GameRegistry.registerItem(Plumedhat, "Plumedhat" );
		GameRegistry.registerItem(Ribbon, "Ribbon" );
		GameRegistry.registerItem(Thiefscap, "Thiefscap" );
		GameRegistry.registerItem(Tiara, "Tiara" );
		GameRegistry.registerItem(Wizardshat, "Wizardshat" );
		GameRegistry.registerItem(Whitehat, "Whitehat" );
		
		GameRegistry.registerItem(Adamantarmor, "Adamantarmor" );
		GameRegistry.registerItem(Adamantvest, "Adamantvest" );
		GameRegistry.registerItem(Aegisshield, "Aegisshield" );
		GameRegistry.registerItem(Blackgarb, "Blackgarb" );
		GameRegistry.registerItem(Blackrobe, "Blackrobe" );
		GameRegistry.registerItem(Blazerobe, "Blazerobe" );
		GameRegistry.registerItem(Boneplate, "Boneplate" );
		GameRegistry.registerItem(Brigandine, "Brigandine" );
		GameRegistry.registerItem(Brintfrock, "Brintfrock" );
		GameRegistry.registerItem(Bronzearmor, "Bronzearmor" );
		GameRegistry.registerItem(Bronzeshield, "Bronzeshield" );
		GameRegistry.registerItem(Carabineermail, "Carabineermail" );
		GameRegistry.registerItem(Chainmail, "Chainmail" );
		GameRegistry.registerItem(Chameleonrobe, "Chameleonrobe" );
		GameRegistry.registerItem(Chocoboshield, "Chocoboshield" );
		GameRegistry.registerItem(Diamondarmor, "Diamondarmor" );
		GameRegistry.registerItem(Dragonmail, "Dragonmail" );
		GameRegistry.registerItem(Ensanguinedshield, "Ensanguinedshield" );
		GameRegistry.registerItem(Everrobe, "Everrobe" );
		GameRegistry.registerItem(flameshield, "flameshield" );
		GameRegistry.registerItem(flurryrobe, "flurryrobe" );
		GameRegistry.registerItem(Gaiagear, "Gaiagear" );
		GameRegistry.registerItem(Galmiafrock, "Galmiafrock" );
		GameRegistry.registerItem(Galmiashoes, "Galmiashoes" );
		GameRegistry.registerItem(Genjiarmor, "Genjiarmor" );
		GameRegistry.registerItem(Genjishield, "Genjishield" );
		GameRegistry.registerItem(Goldenarmor, "Goldenarmor" );
		GameRegistry.registerItem(Hempenrobe, "Hempenrobe" );
		GameRegistry.registerItem(Iceshield, "Iceshield" );
		GameRegistry.registerItem(Ironarmor, "Ironarmor" );
		GameRegistry.registerItem(Judicerscoat, "Judicerscoat" );
		GameRegistry.registerItem(Jujitsugi, "Jujitsugi" );
		GameRegistry.registerItem(Leatherclothing, "Leatherclothing" );
		GameRegistry.registerItem(Linencuirass, "Linencuirass" );
		GameRegistry.registerItem(Lordlyrobe, "Lordlyrobe" );
		GameRegistry.registerItem(Luminousrobe, "Luminousrobe" );
		GameRegistry.registerItem(Magickrobe, "Magickrobe" );
		GameRegistry.registerItem(Magusrobe, "Magusrobe" );
		GameRegistry.registerItem(Materiaarmor, "Materiaarmor" );
		GameRegistry.registerItem(Maximillian, "Maximillian" );
		GameRegistry.registerItem(Minervabustier, "Minervabustier" );
		GameRegistry.registerItem(Miragevest, "Miragevest" );
		GameRegistry.registerItem(Mirrormail, "Mirrormail" );
		GameRegistry.registerItem(Ninjagear, "Ninjagear" );
		GameRegistry.registerItem(Peytral, "Peytral" );
		GameRegistry.registerItem(Platemail, "Platemail" );
		GameRegistry.registerItem(Platinumarmor, "Platinumarmor" );
		GameRegistry.registerItem(Platinumshield, "Platinumshield" );
		GameRegistry.registerItem(Powersash, "Powersash" );
		GameRegistry.registerItem(Reapersrobe, "Reapersrobe" );
		GameRegistry.registerItem(Redrobe, "Redrobe" );
		GameRegistry.registerItem(Reverieshield, "Reverieshield" );
		GameRegistry.registerItem(Roundshield, "Roundshield" );
		GameRegistry.registerItem(Rubbersuit, "Rubbersuit" );
		GameRegistry.registerItem(Sagesrobe, "Sagesrobe" );
		GameRegistry.registerItem(Samitecoat, "Samitecoat" );
		GameRegistry.registerItem(Shieldofthefour, "Shieldofthefour" );
		GameRegistry.registerItem(Silkenrobe, "Silkenrobe" );
		GameRegistry.registerItem(Survivalvest, "Survivalvest" );
		GameRegistry.registerItem(Templarcloth, "Templarcloth" );
		GameRegistry.registerItem(Templarshield, "Templarshield" );
		GameRegistry.registerItem(Thunderrobe, "Thunderrobe" );
		GameRegistry.registerItem(Whiterobe, "Whiterobe" );
		GameRegistry.registerItem(Wygar, "Wygar" );
			
		GameRegistry.registerItem(Angelring, "Angelring" );
		GameRegistry.registerItem(Armguards, "Armguards" );
		GameRegistry.registerItem(Armletofwhispers, "Armletofwhispers" );
		GameRegistry.registerItem(Azuretear, "Azuretear" );
		GameRegistry.registerItem(Battleboots, "Battleboots" );
		GameRegistry.registerItem(Bonearmlets, "Bonearmlets" );
		GameRegistry.registerItem(Bracers, "Bracers" );
		GameRegistry.registerItem(Brigandsgloves, "Brigandsgloves" );
		GameRegistry.registerItem(Condemnerschoker, "Condemnerschoker" );
		GameRegistry.registerItem(Corsageofcorruption, "Corsageofcorruption" );
		GameRegistry.registerItem(Crimsontear, "Crimsontear" );
		GameRegistry.registerItem(Earringsofthedead, "Earringsofthedead" );
		GameRegistry.registerItem(Emphyrealarmband, "Emphyrealarmband" );
		GameRegistry.registerItem(Ewerofdarkness, "Ewerofdarkness" );
		GameRegistry.registerItem(Faerieshoes, "Faerieshoes" );
		GameRegistry.registerItem(Fortunering, "Fortunering" );
		GameRegistry.registerItem(Gaiuscaligae, "Gaiuscaligae" );
		GameRegistry.registerItem(Gauntlets, "Gauntlets" );
		GameRegistry.registerItem(Genjigloves, "Genjigloves" );
		GameRegistry.registerItem(Germinasboots, "Germinasboots" );
		GameRegistry.registerItem(Giftofthejudgesal, "Giftofthejudgesal" );
		GameRegistry.registerItem(Gigaspendant, "Gigaspendant" );
		GameRegistry.registerItem(Goldenamulet, "Goldenamulet" );
		GameRegistry.registerItem(Highseraphsplume, "Highseraphsplume" );
		GameRegistry.registerItem(Magickring, "Magickring" );
		GameRegistry.registerItem(Moonmaiden, "Moonmaiden" );
		GameRegistry.registerItem(Ninjatabi, "Ninjatabi" );
		GameRegistry.registerItem(Orbofminwu, "Orbofminwu" );
		GameRegistry.registerItem(Pinoforder, "Pinoforder" );
		GameRegistry.registerItem(Ragingbrooch, "Ragingbrooch" );
		GameRegistry.registerItem(Redshoes, "Redshoes" );
		GameRegistry.registerItem(Ringofprecepts, "Ringofprecepts" );
		GameRegistry.registerItem(Ringofthewheel, "Ringofthewheel" );
		GameRegistry.registerItem(Rubyearring, "Rubyearring" );
		GameRegistry.registerItem(Scarabcharm, "Scarabcharm" );
		GameRegistry.registerItem(Snowytear, "Snowytear" );
		GameRegistry.registerItem(Spikedboots, "Spikedboots" );
		GameRegistry.registerItem(Sprintshoes, "Sprintshoes" );
		GameRegistry.registerItem(Taintedcufflinks, "Taintedcufflinks" );
		GameRegistry.registerItem(Wingedboots, "Wingedboots" );
		
		
		}

	}


