package fr.toss.FF7;

import java.util.ArrayList;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

import com.sun.xml.internal.bind.v2.schemagen.xmlschema.List;

import cpw.mods.fml.common.registry.GameRegistry;
import fr.toss.common.Main;

public class reciperegister {

	


	public static void init() {
		    GameRegistry.addRecipe(new ItemStack(Main.Brewingstand, 4), new Object[] {" B ", "###", '#', Blocks.cobblestone, 'B', Items.blaze_rod});
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaybrick, 4), new Object[] {"## ", "#! ", '#', ItemRegistry1.subwayparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaybrickcarved, 4), new Object[] {"#! ", "## ", '#', ItemRegistry1.subwayparts,'!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaybrickcracked, 4), new Object[] {"!# ", "## ", '#', ItemRegistry1.subwayparts,'!', Blocks.cobblestone,  });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaybrickmossy, 4), new Object[] {"## ", "!# ", '#', ItemRegistry1.subwayparts,'!', Blocks.cobblestone,  });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaylampoff, 4), new Object[] {"#@#", "@$@", "#@#", '#', ItemRegistry1.subwayparts, '@', Blocks.glass, '$', Items.redstone });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaytile1, 4), new Object[] {"## ", "#! ", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaytile2, 4), new Object[] {"#! ", "## ", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaytile3, 4), new Object[] {"!# ", "## ", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaytile4, 4), new Object[] {"## ", "!# ", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile1, 4), new Object[] {"#!", "#!", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile2, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile3, 4), new Object[] {"!#", "#!", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile4, 4), new Object[] {"#!", "!#", '#', ItemRegistry1.subwayparts, '!', Blocks.stone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile5, 4), new Object[] {"#!", "#!", '#', ItemRegistry1.subwayparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.subwaywalltile6, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.subwayparts, '!', Blocks.cobblestone, });
		    
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab1, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab2, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab3, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab4, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab5, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab6, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab7, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab8, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab9, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab10, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab11, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab12, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab13, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab14, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab15, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab16, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab17, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab18, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab19, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab20, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab21, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab22, 4), new Object[] {"#@#", "@$@", "#@#", '#', ItemRegistry1.darklabparts, '@', Blocks.glass, '$', Items.redstone });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab23, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab24, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab25, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab26, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab27, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab28, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab29, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab30, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab31, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab32, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab33, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.darklab34, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.darklabparts, '!', Blocks.cobblestone, });
		    
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random1, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random2, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random3, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random4, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random5, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random6, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random7, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random8, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random9, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random10, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random11, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random12, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random13, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random14, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random15, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random16, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random17, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random18, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random19, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random20, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random21, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random22, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random23, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random24, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random25, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random26, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random27, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random28, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random29, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random30, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random31, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random32, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random33, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random34, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random35, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random36, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.random37, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.randomparts, '!', Blocks.cobblestone, });
		   
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab1, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab2, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab3, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab4, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab5, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab6, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab7, 1), new Object[] {"#@#", "@$@", "#@#", '#', ItemRegistry1.whitelabparts, '@', Blocks.glass, '$', Items.redstone });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab8, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab9, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab10, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab11, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
		    GameRegistry.addRecipe(new ItemStack(BlockRegistry1.whitelab12, 4), new Object[] {"!#", "!#", '#', ItemRegistry1.whitelabparts, '!', Blocks.cobblestone, });
			  
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Shininglute, 1), new Object[] {"   ", " # ", " ! ", '#', ItemRegistry1.Flutegrass, '!', ItemRegistry1.Strawood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Brillianttheorbo, 1), new Object[] {"   ", " # ", " ! ", '#', ItemRegistry1.Spiralvine, '!', ItemRegistry1.Strawood, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Bronzearmor, 1), new Object[] {"   ", " # ", " ! ", '#', ItemRegistry1.Gikhetlead, '!', ItemRegistry1.Cactusfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Broadsword, 1), new Object[] {"   ", " # ", " ! ", '#', ItemRegistry1.Gikhetlead, '!', ItemRegistry1.Farenpollen, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Platinumarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Platinum, '#', ItemRegistry1.Hedychium, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Platinumshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Platinum, '#', ItemRegistry1.Leucojum, '!', ItemRegistry1.Silverliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Platinumhelmet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Platinum, '#', ItemRegistry1.Peppergrass, '!', ItemRegistry1.Greenliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Mandragora, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mysidiaalloy, '#', ItemRegistry1.Screamroot, '!', ItemRegistry1.Clearsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Onionsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Onion, '!', ItemRegistry1.Crusadertonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Jambiya, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Crusitealloy, '#', ItemRegistry1.Spiralincisor, '!', ItemRegistry1.Fourleafclover, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Cinquedea, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Spiralincisor, '!', ItemRegistry1.Kalos, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Zwillblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zincatite, '#', ItemRegistry1.Blooddarkenedbone, '!', ItemRegistry1.Hedychiumpollen, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kris, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Sturdybone, '!', ItemRegistry1.Tomatostalk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Scramasax, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Xergistin, '#', ItemRegistry1.Pointedhorn, '!', ItemRegistry1.Ballmoss, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kard, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Animalbone, '!', ItemRegistry1.Cactusfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Samsonsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Chocoboskin, '!', ItemRegistry1.Nepenthis, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Vajra, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Hedychium, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Gaebolg, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Telakflower, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Atomosblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Gikhetlead, '!', ItemRegistry1.Farenpollen, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Thorrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Kalos, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Thunderrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Silkbloom, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Thunderrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Sturdyvine, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Minervabustier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Spiralvine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Artemisbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Gemsteel, '!', ItemRegistry1.Moonbloom, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Savethequeen, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Pearlmoss, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Bombarm, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Magickfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lilithrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Magickfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Forcerod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Marriomheather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Goldenskullcap, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Goldcap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Goldenamulet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lowarcana, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Hedychiumpollen, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Goldhairpin, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Pearlmoss, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Talwar, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Aureapollen, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Manganesesaber, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Gemsteel, '!', ItemRegistry1.Fourleafclover, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Harpe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watersigil, '#', ItemRegistry1.Gemsteel, '!', ItemRegistry1.Suspectmushroom, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Shamshir, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Hedychium, });
		    // GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Scorpiantail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Crusitealloy , '!', ItemRegistry1.Aureapollen, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Morningstar, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windcrystal, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Kalos, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Druidmace, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Whisperweed, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Energymace, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Succulentfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ragetsudenbu, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lowarcana, '#', ItemRegistry1.Gungear, '!', ItemRegistry1.Screamroot, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sumihomura, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Goldcap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Adazakura, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Kalos, });
		   // GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Nosada, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Spiralvine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kikuichimonji, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Einherjarium, '!', ItemRegistry1.Hedychiumpollen, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kotetsu, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Goldcap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Osafune, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watersigil, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Leucojum, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ashura, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Suspectmushroom, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kunai, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Primapetal, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Goldenaxe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.Goldcap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Goldenarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Dipraeubronze, '#', ItemRegistry1.Tyranthide, '!', ItemRegistry1.Tomatostalk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Tigerfangs, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantite, '#', ItemRegistry1.Tannedbeasthide, '!', ItemRegistry1.Kalos, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Powersash, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mysidiaalloy, '#', ItemRegistry1.Gianttannedhide, '!', ItemRegistry1.Onion, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Jujitsugi, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Primepelt, '!', ItemRegistry1.Pearlmoss, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Headband, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Trustyfryingpan, '#', ItemRegistry1.Rabbittail, '!', ItemRegistry1.Powerfruit, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Survivor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bundleofneedles, '#', ItemRegistry1.Primepelt, '!', ItemRegistry1.Tomatostalk, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Survivalvest, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gungear, '#', ItemRegistry1.Tigerhide, '!', ItemRegistry1.Powerfruit, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Greenberet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cursedcoin, '#', ItemRegistry1.Tigerhide, '!', ItemRegistry1.Malborovine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Jackknife, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Snakeskin, '!', ItemRegistry1.Tinymushrooms, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Templarcloth, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Einherjarium, '#', ItemRegistry1.Pinktail, '!', ItemRegistry1.Aureapollen, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Rubbersuit, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mysidiaalloy, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.Magickfruit, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Wygar, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Orichalcum, '#', ItemRegistry1.Pinktail, '!', ItemRegistry1.Leucojum, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Brigandine, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.Moonbloom, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Chainmail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Tannedhide, '!', ItemRegistry1.Ladiestresses, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Tournesol, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Scarletite, '!', ItemRegistry1.Emperorscale, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Samitecoat, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Alraunedrill, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Silverrapier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Trustyfryingpan, '!', ItemRegistry1.Mirrorscale, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Silvercannon, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Clockgear, '!', ItemRegistry1.Zingupearlshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Silverbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Wyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Silversword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Insecthusk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Whitefangs, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Blooddarkenedbone, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Iceshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Icebrand, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Adamantalloy, '!', ItemRegistry1.Molting, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Icelance, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Sanativeneedle, '!', ItemRegistry1.Furyfragments, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Soulsaber, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firecrystal, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lavaspear, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Animalbone, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Flametongue, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Zingupearl, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Scarletrapier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Sanativeneedle, '!', ItemRegistry1.Bombshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Venusblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Bombshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lotusmace, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Ancientturtleshell, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.flameshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Cursedcoin, '!', ItemRegistry1.Greatserpentfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Flamerod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Wyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Blazerobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Bombshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Firewheelrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Ironcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Risingsun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Adamantalloy, '!', ItemRegistry1.Bombshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sunblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Bombshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Crownscepter, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Damascus, '!', ItemRegistry1.Beastlordhorn, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Fortunering, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Battlewyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Defender, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Furyfragments, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Staffofprotection, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Coralfragments, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Armguards, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Turtleshell, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Emphyrealarmband, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lowarcana, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Starfragments, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Stardustrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Starfragments, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Hereticrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Deathclaws, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Boneplate, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Blooddarkenedbone, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Blackquena, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Skull, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Apocalypse, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Skull, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Diabolique, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Bloodsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Cursedcoin, '!', ItemRegistry1.Spiralincisor, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Hadesbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Clockgear, '!', ItemRegistry1.Blooddarkenedbone, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Archsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Codscale, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lohengrin, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Codscale, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ragnarok, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Zingupearl, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lionheart, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Dragonbone, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Templarshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Starfragments, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Maximillian, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lowarcana, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Wyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Restorer, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Orichalcum, '!', ItemRegistry1.Wyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Burglarsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Dragonbone, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Bustersword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Crookedfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ebonblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Vampyrfang, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Paraibablade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Lamiascale, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Pearlblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Zingupearlshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ogunblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Gimblestalk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sweepblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Gikhetlead, '!', ItemRegistry1.Animalbone, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Springstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watersigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Healingwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Aquasaber, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Healingwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Murasame, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Healingwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Blueleafflute, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watersigil, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Unpurifiedether, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Bluesaber, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Trustyfryingpan, '!', ItemRegistry1.Freshwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Zanmato, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Bundleofneedles, '!', ItemRegistry1.Aquagelac, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Amanomurakumo, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Gemsteel, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Healchime, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Sweetsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Godhand, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Unpurifiedether, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Vitanova, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Crusitealloy, '!', ItemRegistry1.Clearsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Thefallenangel, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Herotonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Excalibur, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Crusadertonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Outsider, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Clearsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Peacemaker, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Silverliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Longbarrel, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Chaosrifle, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Gungear, '!', ItemRegistry1.Silverliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Giotgun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Gungear, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lostgun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Gungear, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Riotgun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Clockgear, '!', ItemRegistry1.Greenliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Aiotgun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Sanativeneedle, '!', ItemRegistry1.Cloudysap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Diamondarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Dipraeubronze, '#', ItemRegistry1.Battlewyrmcarapace, '!', ItemRegistry1.Sweetsap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Diamondhelm, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Zingupearl, '!', ItemRegistry1.Bittersap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Diamondsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zinconium, '#', ItemRegistry1.Pointedhorn, '!', ItemRegistry1.Bittersap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Giantshelmet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Crusitealloy, '#', ItemRegistry1.Beastlordhorn, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Hanyamask, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Crusitealloy, '#', ItemRegistry1.Blooddarkenedbone, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Closehelmet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.BoneChips, '!', ItemRegistry1.Malborowine, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Barbut, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Crookedfang, '!', ItemRegistry1.Greenliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Tonberrian, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Scarletite, '#', ItemRegistry1.Wyvernfang, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Orichalcumdirk, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Orichalcum, '#', ItemRegistry1.Alraunedrill, '!', ItemRegistry1.Bittersap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Khukuri, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Bombshell, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Rondel, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Xergistin, '#', ItemRegistry1.Insecthusk, '!', ItemRegistry1.Malborowine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Joyeuse, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Trustyfryingpan, '#', ItemRegistry1.Zingupearl, '!', ItemRegistry1.Aquagelac, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Magemasher, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Sanativeneedle, '#', ItemRegistry1.Sturdybone, '!', ItemRegistry1.Aquagelac, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Fleuret, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Sanativeneedle, '#', ItemRegistry1.Molting, '!', ItemRegistry1.Freshwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Stinger, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Sanativeneedle, '#', ItemRegistry1.Lamiascale, '!', ItemRegistry1.Freshwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Rocketpunch, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bundleofneedles, '#', ItemRegistry1.Ancientturtleshell, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Guangcannon, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Greatserpentfang, '!', ItemRegistry1.Fiendsblood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Dromaeo, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Skull, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Brevis, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Agedturtleshell, '!', ItemRegistry1.Fiendsblood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Massivebazooka, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Coralfragments, '!', ItemRegistry1.Sweetsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Diklum, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Dragonbone, '!', ItemRegistry1.Bittersap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ligatur, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Battlewyrmcarapace, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Supernalray, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Sturdybone, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Omniscannon, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Clockgear, '#', ItemRegistry1.Ironcarapace, '!', ItemRegistry1.Cloudysap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Ironarmor, 1), new Object[] {"   ", " # ",  " ! ", '#', ItemRegistry1.Trustyfryingpan, '!', ItemRegistry1.Zingupearlshell, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Ironhelmet, 1), new Object[] {"   ", " # ",  " ! ", '#', ItemRegistry1.Trustyfryingpan, '!', ItemRegistry1.Turtleshell, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Greataxe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Cockatriceskin, '!', ItemRegistry1.Gimblestalk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Fransisca, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Leestone, '#', ItemRegistry1.Rabbitpelt, '!', ItemRegistry1.Spiralincisor, });
		    //GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Slasher, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Tigerhide, '!', ItemRegistry1.Battlewyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Hammerhead, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Coeurlpelt, '!', ItemRegistry1.Greatserpentfang, });
		    //GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Broadaxe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Ratpelt, '!', ItemRegistry1.Mirrorpelt, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Bonearmlets, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Tannedbeasthide, '!', ItemRegistry1.Blooddarkenedbone, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Gauntlets, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Platinum, '#', ItemRegistry1.Tannedtyranthide, '!', ItemRegistry1.Wyrmcarapace, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Bracers, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zincatite, '#', ItemRegistry1.Qualityhide, '!', ItemRegistry1.Dragonbone, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Reverieshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Scarletite, '#', ItemRegistry1.Tyranthide, '!', ItemRegistry1.Wyvernfang, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Shieldofthefour, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantite, '#', ItemRegistry1.Pinktail, '!', ItemRegistry1.Ancientturtleshell, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Chocoboshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Chocoboskin, '!', ItemRegistry1.Alraunedrill, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Aegisshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Tannedtyranthide, '!', ItemRegistry1.Spiralincisor, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Roundshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Qualitypelt, '!', ItemRegistry1.Lamiascale, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Dragonwhisker, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Einherjarium, '#', ItemRegistry1.Wyvernfang, '!', ItemRegistry1.Wyvernwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Trident, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Moonring, '#', ItemRegistry1.Codscale, '!', ItemRegistry1.Wyvernwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kainslance, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Crusitealloy, '#', ItemRegistry1.Vampyrfang, '!', ItemRegistry1.blackthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Partisan, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Dipraeubronze, '#', ItemRegistry1.Wyrmcarapace, '!', ItemRegistry1.Velvet, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Javelin, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Xergistin, '#', ItemRegistry1.Animalbone, '!', ItemRegistry1.Wool, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Catclaws, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mythril, '#', ItemRegistry1.Qualityhide, '!', ItemRegistry1.Sweetsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Dreamclaws, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zincatite, '#', ItemRegistry1.Gianttannedhide, '!', ItemRegistry1.Cloudysap, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Adamantarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthcrystal, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Pinktail, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Adamantblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Cockatriceskin, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Adamantvest), new Object[] {" @ ", " # ", " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Adamantalloy, '!', ItemRegistry1.Rattail, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Battlebamboo, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Cursedcoin, '!', ItemRegistry1.Qualitypelt, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Battleboots, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Ratpelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Gleisburst, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watercrystal, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Tannedbeasthide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Magickhands, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormcrystal, '#', ItemRegistry1.Bundleofneedles, '!', ItemRegistry1.Cockatriceskin, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kaiserknuckles, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Adamantalloy, '!', ItemRegistry1.Gianttannedhide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Poisonknuckles, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Xergistin, '!', ItemRegistry1.Battail, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Metalknuckles, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Wolfpelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Estrella, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watercrystal, '#', ItemRegistry1.Scarletite, '!', ItemRegistry1.Primepelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Rhomphaia, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Tannedbeasthide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Beastsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Gianttannedhide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Claymore, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Adamantite, '!', ItemRegistry1.Tannedtyranthide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Stribog, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Gianttannedhide, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Elcid, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Waterstone, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Coeurlpelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Predator, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Gikhetlead, '!', ItemRegistry1.Wolfpelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Falchion, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Ratpelt, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Judicerscoat, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormcrystal, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Primepelt, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Colichemarde, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Damascus, '!', ItemRegistry1.Tannedtyranthide, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Rubyearring, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Zodiacore, '!', ItemRegistry1.Pinktail, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ayvuirred, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firecrystal, '#', ItemRegistry1.Orichalcum, '!', ItemRegistry1.Spidersilk, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Redrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Einherjarium, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Redshoes, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Cursedcoin, '!', ItemRegistry1.Largefeather, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Chillrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Finewool, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.flurryrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Agedlinenthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sleetrod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Zinconium, '!', ItemRegistry1.Dirtywool, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Miragevest, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Gemsteel, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Mirrormail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Epeeprisme, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Faeriewing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Windsongrapier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windcrystal, '#', ItemRegistry1.Mysidiaalloy, '!', ItemRegistry1.Wyvernwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Galesword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Damascus, '!', ItemRegistry1.Batwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Airblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Dipraeubronze, '!', ItemRegistry1.Giantfeather, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Djinnflyssa, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Cursedcoin, '!', ItemRegistry1.Ahrimanwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Windslashbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Cruzlebrass, '!', ItemRegistry1.Smallfeather, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Masamune, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Moonring, '#', ItemRegistry1.Clearsap, '!', ItemRegistry1.Spidersilk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Materiablade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mythril, '#', ItemRegistry1.Herotonic, '!', ItemRegistry1.Demonfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Materiaarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mysidiaalloy, '#', ItemRegistry1.Crusadertonic, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Dragonmail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantite, '#', ItemRegistry1.Silverliquid, '!', ItemRegistry1.Whitethread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Carabineermail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Malborowine, '!', ItemRegistry1.Superiorsilkthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Platemail, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Dipraeubronze, '#', ItemRegistry1.Greenliquid, '!', ItemRegistry1.Silkthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Mjolnir, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Scarletite, '#', ItemRegistry1.Quince, '!', ItemRegistry1.Unpurifiedether, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sledgehammer, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cursedcoin, '#', ItemRegistry1.Gurnat, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Warhammer, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Cottonflue, '!', ItemRegistry1.Cloudysap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ironhammer, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Xergistin, '#', ItemRegistry1.Spruce, '!', ItemRegistry1.Freshwater, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Sagesrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Stradivari, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Staffofthemagi, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Godwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sagecrosier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Rosebranch, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Angelring, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Wyrmtwig, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Staffofblessings, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Platinum, '!', ItemRegistry1.Divariwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Femmefatale, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firecrystal, '#', ItemRegistry1.Bundleofneedles, '!', ItemRegistry1.Kuraisleboxwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Madu, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Snowcrystal, '#', ItemRegistry1.Moonring, '!', ItemRegistry1.Mahbeny, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Guptiaga, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Einherjarium, '!', ItemRegistry1.Kempas, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Flamberge, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icestone, '#', ItemRegistry1.Sanativeneedle, '!', ItemRegistry1.Moonwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Estoc, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Sanativeneedle, '!', ItemRegistry1.Birch, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Eightflutedpole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Goldchalice, '!', ItemRegistry1.Redgeeps, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ivorypole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Icesigil, '#', ItemRegistry1.Mythril, '!', ItemRegistry1.Agathis, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Esztambaton, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Divariwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Gokuupole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Bodyceffyl, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Qualitylumber, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Zephyrpole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Zincatite, '!', ItemRegistry1.Mapewood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ironpole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Waltwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Cypresspole, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Spruce, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sanjiegun, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Leestone, '!', ItemRegistry1.Pagodawood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Luabreaker, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Mirrorscale, '!', ItemRegistry1.Redgeeps, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Swordbreaker, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Adamantalloy, '#', ItemRegistry1.Sturdybone, '!', ItemRegistry1.Moonwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Hardedge, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zodiacore, '#', ItemRegistry1.Greatserpentfang, '!', ItemRegistry1.Danbukwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Maxsoathbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mysidiaalloy, '#', ItemRegistry1.Blooddarkenedbone, '!', ItemRegistry1.Wyrmtwig, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Gastrophetes, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zincatite, '#', ItemRegistry1.Alraunedrill, '!', ItemRegistry1.Qualitylumber, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Masterbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zodiacore, '#', ItemRegistry1.Gimblestalk, '!', ItemRegistry1.Kuraisleboxwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Twinbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Sturdybone, '!', ItemRegistry1.Danbukwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Mastersword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Scarletite, '#', ItemRegistry1.Beastlordhorn, '!', ItemRegistry1.Godwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Vigilante, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Orichalcum, '#', ItemRegistry1.Emperorscale, '!', ItemRegistry1.Kuraisleboxwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ogrenix, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zodiacore, '#', ItemRegistry1.Zingupearl, '!', ItemRegistry1.Pagodawood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Zwheihander, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zodiacore, '#', ItemRegistry1.Skull, '!', ItemRegistry1.Qualitylumber, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Dagriohm, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Ironcarapace, '!', ItemRegistry1.Mapewood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Ancientsword, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Sanativeneedle, '#', ItemRegistry1.Pointedhorn, '!', ItemRegistry1.Spruce, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Xanqbras, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Xergistin, '#', ItemRegistry1.Insecthusk, '!', ItemRegistry1.Birch, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Barong, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Animalbone, '!', ItemRegistry1.Waltwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Frigidviol, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Einherjarium, '#', ItemRegistry1.Starfragments, '!', ItemRegistry1.Kempas, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Wartrumpet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Trustyfryingpan, '#', ItemRegistry1.Agedturtleshell, '!', ItemRegistry1.Mapewood, });
		  //  GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Glassbell, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Skull, '!', ItemRegistry1.Moonwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Demonbell, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gikhetlead, '#', ItemRegistry1.Skull, '!', ItemRegistry1.Danbukwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Perseusbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gemsteel, '#', ItemRegistry1.Quince, '!', ItemRegistry1.Spidersilk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Fanatic, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Wyrmtwig, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Satyrflute, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Damascus, '#', ItemRegistry1.Rosebranch, '!', ItemRegistry1.Batwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Oblige, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Dipraeubronze, '#', ItemRegistry1.Cottonflue, '!', ItemRegistry1.Superiorsilkthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kwigonblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Platinum, '#', ItemRegistry1.Birch, '!', ItemRegistry1.Agedlinenthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Tonfa, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cruzlebrass, '#', ItemRegistry1.Agathis, '!', ItemRegistry1.Ahrimanwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Conchshell, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Zincatite, '#', ItemRegistry1.Cottonflue, '!', ItemRegistry1.Softcotton, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Ninjatabi, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primetannedhide, '#', ItemRegistry1.Wyvernfang, '!', ItemRegistry1.Demonfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Brigandsgloves, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Rabbittail, '#', ItemRegistry1.Battlewyrmcarapace, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Ninjagear, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Rabbittail, '#', ItemRegistry1.Emperorscale, '!', ItemRegistry1.Faeriewing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Blackgarb, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Qualityhide, '#', ItemRegistry1.Emperorscale, '!', ItemRegistry1.Giantfeather, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Shadowblade, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Battail, '#', ItemRegistry1.Molting, '!', ItemRegistry1.Largefeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Genjiarmor, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primetannedhide, '#', ItemRegistry1.Beastlordhorn, '!', ItemRegistry1.Kuraisleboxwood, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Genjishield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tannedbeasthide, '#', ItemRegistry1.Ancientturtleshell, '!', ItemRegistry1.Wyrmtwig, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Genjihelm, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tannedbeasthide, '#', ItemRegistry1.Coralfragments, '!', ItemRegistry1.Godwood, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Genjigloves, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tyranthide, '#', ItemRegistry1.Agedturtleshell, '!', ItemRegistry1.Wyrmtwig, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Joker, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cockatriceskin, '#', ItemRegistry1.Aureapollen, '!', ItemRegistry1.Fiendsblood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Twoofclubs, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cockatriceskin, '#', ItemRegistry1.Screamroot, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Sixofdiamonds, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tannedbeasthide, '#', ItemRegistry1.Malboroflower, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Aceofspades, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Pinktail, '#', ItemRegistry1.Onion, '!', ItemRegistry1.Unpurifiedether, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Kingofhearts, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primetannedhide, '#', ItemRegistry1.Malboroflower, '!', ItemRegistry1.Clearsap, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Queenofclubs, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primepelt, '#', ItemRegistry1.Hedychium, '!', ItemRegistry1.Silverliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Jackofdiamonds, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Cockatriceskin, '#', ItemRegistry1.Magickfruit, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Eightofhearts, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Gianttannedhide, '#', ItemRegistry1.Onion, '!', ItemRegistry1.Silverliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Fourofspades, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Rattail, '#', ItemRegistry1.Recallgrass, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Brintfrock, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primetannedhide, '#', ItemRegistry1.Emperorscale, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Galmiafrock, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Primepelt, '#', ItemRegistry1.Emperorscale, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Scarabcharm, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Coeurlpelt, '!', ItemRegistry1.Blooddarkenedbone, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Blackhat, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.blackthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Blackrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Qualitypelt, '!', ItemRegistry1.blackthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Lordlyrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Higharcana, '#', ItemRegistry1.Pinktail, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Luminousrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Primepelt, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Chameleonrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Coeurlpelt, '!', ItemRegistry1.Softcotton, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Silkenrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Rabbitpelt, '!', ItemRegistry1.Silkthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Tiara, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormsigil, '#', ItemRegistry1.Qualitypelt, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Thiefscap, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkstone, '#', ItemRegistry1.Tannedtyranthide, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Wizardshat, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Soulceffyl, '#', ItemRegistry1.Tannedhide, '!', ItemRegistry1.Velvet, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Circlet, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Rabbitpelt, '!', ItemRegistry1.Wool, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Gaiuscaligae, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormcrystal, '#', ItemRegistry1.Tannedbeasthide, '!', ItemRegistry1.Demonfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Germinasboots, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthcrystal, '#', ItemRegistry1.Tyranthide, '!', ItemRegistry1.Spidersilk, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Sprintshoes, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Rabbittail, '!', ItemRegistry1.Superiorsilkthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Spikedboots, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firestone, '#', ItemRegistry1.Wolfpelt, '!', ItemRegistry1.Finewool, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Galmiashoes, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windcrystal, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Wingedboots, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windcrystal, '#', ItemRegistry1.Rabbittail, '!', ItemRegistry1.Batwing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Everrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Primetannedhide, '!', ItemRegistry1.Wyvernwing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Orbofminwu, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lowarcana, '#', ItemRegistry1.Crusadertonic, '!', ItemRegistry1.Rainbowthread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Ensanguinedshield, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Blooddarkenedbone, '#', ItemRegistry1.Fiendsblood, '!', ItemRegistry1.Demonfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Reapersrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Skull, '#', ItemRegistry1.Fiendsblood, '!', ItemRegistry1.Demonfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Whitehat, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Starfragments, '!', ItemRegistry1.Whitethread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Whiterobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Zingupearl, '!', ItemRegistry1.Whitethread, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Faerieshoes, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Starfragments, '#', ItemRegistry1.Stradivari, '!', ItemRegistry1.Faeriewing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Faerieharp, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Alraunedrill, '#', ItemRegistry1.Mahbeny, '!', ItemRegistry1.Faeriewing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Magickrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Darkcrystal, '#', ItemRegistry1.Magickfruit, '!', ItemRegistry1.Batwing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Magickring, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Fourleafclover, '!', ItemRegistry1.Smallfeather, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Magusrobe, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tarkovcrystal, '#', ItemRegistry1.Tinymushrooms, '!', ItemRegistry1.Softcotton, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Cheerstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Fourleafclover, '#', ItemRegistry1.Gurnat, '!', ItemRegistry1.Herotonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Malbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Malborovine, '#', ItemRegistry1.Godwood, '!', ItemRegistry1.Malborowine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Endaroyascriptures, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Screamroot, '#', ItemRegistry1.Stradivari, '!', ItemRegistry1.Putridliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Tomeofending, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Kalos, '#', ItemRegistry1.Quince, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Veilofwiyu, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Hedychiumpollen, '#', ItemRegistry1.Kempas, '!', ItemRegistry1.Yellowliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Enaviachronicles, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Tinymushrooms, '#', ItemRegistry1.Kempas, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Thearnathglyphs, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Marriomheather, '#', ItemRegistry1.Qualitylumber, '!', ItemRegistry1.Malborowine, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Urutanannals, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Ladiestresses, '#', ItemRegistry1.Qualitylumber, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Battlefolio, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Silkbloom, '#', ItemRegistry1.Cottonflue, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Magemanual, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Succulentfruit, '#', ItemRegistry1.Waltwood, '!', ItemRegistry1.Foulliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Nikebow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Spiralvine, '!', ItemRegistry1.Divariwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Judicersstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Stormstone, '#', ItemRegistry1.Recallgrass, '!', ItemRegistry1.Waltwood, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Barette, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Alraunedrill, '#', ItemRegistry1.Kalos, '!', ItemRegistry1.Gurnat, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Cachusha, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Coralfragments, '#', ItemRegistry1.Fourleafclover, '!', ItemRegistry1.Pagodawood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Crescentbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Beastlordhorn, '#', ItemRegistry1.Aureapollen, '!', ItemRegistry1.Mahbeny, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Targetbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Greatserpentfang, '#', ItemRegistry1.Suspectmushroom, '!', ItemRegistry1.Kuraisleboxwood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Yoichibow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Agedturtleshell, '#', ItemRegistry1.Spiralvine, '!', ItemRegistry1.Quince, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Nailbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Spiralincisor, '#', ItemRegistry1.Malborovine, '!', ItemRegistry1.Gurnat, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Thornbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Sturdybone, '#', ItemRegistry1.Spiralvine, '!', ItemRegistry1.Kempas, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Longbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Molting, '#', ItemRegistry1.Sturdyvine, '!', ItemRegistry1.Mapewood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Charbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Animalbone, '#', ItemRegistry1.Sturdyvine, '!', ItemRegistry1.Redgeeps, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Zeusmace, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Godwood, '!', ItemRegistry1.Herotonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Lifecrosier, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watercrystal, '#', ItemRegistry1.Rosebranch, '!', ItemRegistry1.Unpurifiedether, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Healingstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Waltwood, '!', ItemRegistry1.Healingwater, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Cleansingstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Holystone, '#', ItemRegistry1.Waltwood, '!', ItemRegistry1.Crusadertonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Nirvana, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Mahbeny, '!', ItemRegistry1.Crusadertonic, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Pomegranatestaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Firesigil, '#', ItemRegistry1.Pagodawood, '!', ItemRegistry1.Fiendsblood, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Serpentstaff, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Mindceffyl, '#', ItemRegistry1.Divariwood, '!', ItemRegistry1.Strangeliquid, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Arbalest, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Gurnat, '!', ItemRegistry1.Wyvernwing, });
		    GameRegistry.addRecipe(new ItemStack(ArmorRegistry.Gaiagear, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthsigil, '#', ItemRegistry1.Rosebranch, '!', ItemRegistry1.Finewool, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Terrerod, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Agathis, '!', ItemRegistry1.Spidersilk, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Huntsmansbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Earthstone, '#', ItemRegistry1.Spruce, '!', ItemRegistry1.Agedlinenthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Seventhheaven, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Lightcrystal, '#', ItemRegistry1.Kuraisleboxwood, '!', ItemRegistry1.Windslicerpinion, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Marduk, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Pagodawood, '!', ItemRegistry1.Batwing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Elfinbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windsigil, '#', ItemRegistry1.Kuraisleboxwood, '!', ItemRegistry1.Faeriewing, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Huntingbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Watersigil, '#', ItemRegistry1.Agathis, '!', ItemRegistry1.Silkthread, });
		    GameRegistry.addRecipe(new ItemStack(ItemRegistry1.Cranequinbow, 1), new Object[] {" @ ", " # ",  " ! ",'@', ItemRegistry1.Windstone, '#', ItemRegistry1.Danbukwood, '!', ItemRegistry1.Ahrimanwing, });
		   
		    
		    
		    
		    
		    
		    
		    
		    
		}

	}


